=== Tareltos/webTask/src/main/resources/candiesdscr.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/candies" xmlns:tns="http://www.example.com/candies"
        elementFormDefault="qualified">

    <element name="candies">
        <complexType>
            <sequence>
                <element ref="tns:candy" minOccurs="2" maxOccurs="5"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="candy">
        <sequence>
            <element name="date" type="gYearMonth"/>
            <element name="energy" type="double"/>
            <element name="ingredients" type="tns:ingredients"/>
            <element name="energyvalue" type="tns:energyvalue"/>
            <element name="description" type="tns:validateDescr"></element>
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
        <attribute name="production" type="string" use="optional"></attribute>
    </complexType>
    <simpleType name="validateDescr">
        <restriction base="string">
            <pattern value="([^0-9]{0,30})?"/>
        </restriction>
    </simpleType>

    <complexType name="ingredients">
        <sequence>
            <element name="water" type="boolean"></element>
            <element name="sugar" type="double"></element>
            <element name="fructose" type="double"></element>
            <element name="vanillin" type="double"></element>
        </sequence>
        <attribute name="chocolatetype">
            <simpleType>
                <restriction base="string">
                    <enumeration value="white"/>
                    <enumeration value="black"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="energyvalue">
        <sequence>
            <element name="proteins" type="double"></element>
            <element name="fats" type="double"></element>
            <element name="carbohydrates" type="double"></element>
        </sequence>
    </complexType>

    <complexType name="caramel">
        <complexContent>
            <extension base="tns:candy">
                <attribute name="type" type="string" fixed="Caramel"/>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="chocolate">
        <complexContent>
            <extension base="tns:candy">
                <attribute name="type">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Chocolate With filling"/>
                            <enumeration value="Chocolate Without filling"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <element name="candy" type="tns:candy" abstract="true"></element>
    <element name="caramel" type="tns:caramel" substitutionGroup="tns:candy"></element>
    <element name="chocolate" type="tns:chocolate" substitutionGroup="tns:candy"></element>


</schema>


        <!--Конфеты
Name – название конфеты.
Energy– калорийность (ккал).
Type (должно быть несколько) – тип конфеты (карамель, шоколадная [с начинкой либо нет]).
Ingredients (должно быть несколько) – ингредиенты: вода, сахар (в мг), фруктоза (в мг), тип шоколада (для шоколадных), ванилин (в мг)
Value – пищевая ценность: белки (в гр.), жиры (в гр.) и углеводы (в гр.).
Production – предприятие-изготовитель. -->

=== Tareltos/webTask/src/test/resources/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/candies"
         xsi:schemaLocation="http://www.example.com/candies candiesdscr.xsd">

    <chocolate name="Chocolate" type="Chocolate With filling" production="Milka">
        <date>2018-01</date>
        <energy>560.00</energy>
        <ingredients chocolatetype="white">
            <water>true</water>
            <sugar>0.015</sugar>
            <fructose>0.14</fructose>
            <vanillin>0.01</vanillin>
        </ingredients>
        <energyvalue>
            <proteins>0.01</proteins>
            <fats>2.0</fats>
            <carbohydrates>1.5</carbohydrates>
        </energyvalue>
        <description></description>
    </chocolate>
    <caramel name="Caramel01" production="CARAMEL OOO">
        <date>2018-02</date>
        <energy>433</energy>
        <ingredients>
            <water>true</water>
            <sugar>0.5</sugar>
            <fructose>0.4</fructose>
            <vanillin>0.45</vanillin>
        </ingredients>
        <energyvalue>
            <proteins>0.01</proteins>
            <fats>154</fats>
            <carbohydrates>142</carbohydrates>
        </energyvalue>
        <description>Good</description>
    </caramel>
    <chocolate name="AlpGold" type="Chocolate Without filling" production="ApGold">
        <date>2017-11</date>
        <energy>451</energy>
        <ingredients chocolatetype="black">
            <water>false</water>
            <sugar>45</sugar>
            <fructose>11</fructose>
            <vanillin>48</vanillin>
        </ingredients>
        <energyvalue>
            <proteins>1</proteins>
            <fats>17</fats>
            <carbohydrates>23.0</carbohydrates>
        </energyvalue>
        <description>Bitter chocolate</description>
    </chocolate>
</candies>

=== Tareltos/webTask/src/main/resources/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/candies"
         xsi:schemaLocation="http://www.example.com/candies candiesdscr.xsd">

    <chocolate name="Choco" type="Chocolate With filling">
        <date>2018-01</date>
        <energy>560.00</energy>
        <ingredients chocolatetype="black">
            <water>true</water>
            <sugar>0.015</sugar>
            <fructose>0.14</fructose>
            <vanillin>0.01</vanillin>
        </ingredients>
        <energyvalue>
            <proteins>0.01</proteins>
            <fats>2.0</fats>
            <carbohydrates>1.5</carbohydrates>
        </energyvalue>
        <description></description>
    </chocolate>
    <caramel name="CarPar" type="Caramel" production="Milka">
        <date>2018-02</date>
        <energy>433</energy>
        <ingredients>
            <water>true</water>
            <sugar>0.5</sugar>
            <fructose>0.4</fructose>
            <vanillin>0.45</vanillin>
        </ingredients>
        <energyvalue>
            <proteins>0.01</proteins>
            <fats>154</fats>
            <carbohydrates>142</carbohydrates>
        </energyvalue>
        <description>Good</description>
    </caramel>
    <chocolate name="Ch2" type="Chocolate Without filling" production="Pr2">
        <date>2017-11</date>
        <energy>451</energy>
        <ingredients>
            <water>false</water>
            <sugar>45</sugar>
            <fructose>11</fructose>
            <vanillin>48</vanillin>
        </ingredients>
        <energyvalue>
            <proteins>1</proteins>
            <fats>17</fats>
            <carbohydrates>23.0</carbohydrates>
        </energyvalue>
        <description>Bitter chocolate</description>
    </chocolate>
    <caramel name="CaramSS" type="Caramel">
        <date>2017-01</date>
        <energy>423</energy>
        <ingredients>
            <water>true</water>
            <sugar>324</sugar>
            <fructose>24</fructose>
            <vanillin>27</vanillin>
        </ingredients>
        <energyvalue>
            <proteins>44</proteins>
            <fats>2</fats>
            <carbohydrates>4151</carbohydrates>
        </energyvalue>
        <description>Very tasty</description>
    </caramel>
</candies>
